BEGIN;

  CREATE TABLE
  IF NOT EXISTS accomodations
  (
  id integer PRIMARY key  generated by DEFAULT as IDENTITY,
  accomdation text not null,
  description text not null,
  currentday date not null,
  fulfilled text not null,
  accom_id integer REFERENCES students
  (id) on
  delete cascade

);

  commit;